[build]
builder = "nixpacks"
buildCommand = "cd server && npm run build"
watchPaths = ["server/**"]

[deploy]
startCommand = "cd server && npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"

# Configurações de proxy para rotas públicas
[environments.production.healthcheck]
path = "/api/"
interval = "30s"
timeout = "10s"
retries = 3 